module CrySim
  module Diagram
    # Model -> SVG renderer (v0.1): simplified Sugiyama layered layout.
    # Sources on the left, sinks on the right, orthogonal wires, feedback
    # wires routed below the diagram. Glyphs follow control-diagram
    # conventions (gain triangle, sum circle with signs, num/den fraction).
    class SvgRenderer
      GAP_X    =  80.0
      GAP_Y    =  45.0
      MARGIN   =  40.0
      LANE_GAP =  28.0

      record Box, x : Float64, y : Float64, w : Float64, h : Float64 do
        def out_port(port : Int32, n : Int32) : Tuple(Float64, Float64)
          {x + w, y + h * (port + 1) / (n + 1)}
        end

        def in_port(port : Int32, n : Int32) : Tuple(Float64, Float64)
          {x, y + h * (port + 1) / (n + 1)}
        end
      end

      # `result`, when given, draws a small sparkline of each normal wire's
      # logged signal next to its label (used by Model#report /
      # SimResult#report). nil for a plain structural diagram. `highlight`
      # names a block to render in error colors (see Model#render_error).
      def initialize(@model : Model, @result : SimResult? = nil, @highlight : String? = nil)
        @boxes = {} of Int32 => Box
        @layer_of = Array(Int32).new(@model.blocks.size, 0)
        # (left_x, right_x) of each column, spanning its widest block —
        # used to route lane wires clear of every block in a column, not
        # just the specific block a wire happens to start/end at (which
        # may be narrower than a sibling stacked in the same column).
        @col_x = [] of Tuple(Float64, Float64)
      end

      def render(path : String)
        html = <<-HTML
        <!DOCTYPE html>
        <html>
        <head>
          <title>CrySim - #{@model.name}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background: #0f172a; color: #f8fafc; }
            .container { max-width: 1100px; margin: 0 auto; background: #1e293b; padding: 30px; border-radius: 12px; overflow-x: auto; }
            h1 { color: #38bdf8; font-weight: 400; text-align: center; }
            .footer { font-size: 12px; color: #64748b; text-align: center; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>#{@model.name}</h1>
            #{to_svg}
            <div class="footer">Generated by CrySim v#{VERSION} — hover blocks for parameters</div>
          </div>
        </body>
        </html>
        HTML
        File.write(path, html)
      end

      def to_svg : String
        blocks = @model.blocks
        layers = assign_layers
        layers.each_with_index { |col, li| col.each { |bi| @layer_of[bi] = li } }

        # Non-feedback wires that skip over one or more intermediate
        # columns (e.g. a reference signal fanned out straight to a Scope
        # past the whole controller chain) cannot use the simple one-bend
        # router below without drawing straight through the blocks sitting
        # in those intermediate columns. They get routed over a dedicated
        # lane above the diagram instead — the same idea as the feedback
        # lanes below, mirrored.
        top_wires = @model.wires.reject { |w| @model.feedback_wires.includes?(w) }
          .select { |w| @layer_of[@model.block_index[w.dst]] - @layer_of[@model.block_index[w.src]] > 1 }
        top_wires_set = top_wires.to_set
        top_offset = top_wires.empty? ? 0.0 : (MARGIN / 2 + top_wires.size * LANE_GAP)

        compute_boxes(layers, top_offset, top_wires_set)

        width = @boxes.values.max_of(&.x) + @boxes.values.max_of(&.w) + MARGIN
        base_h = @boxes.values.max_of { |b| b.y + b.h } + MARGIN
        fb_wires = @model.wires.select { |w| @model.feedback_wires.includes?(w) }
        height = base_h + fb_wires.size * LANE_GAP + (fb_wires.empty? ? 0.0 : MARGIN / 2)

        String.build do |svg|
          svg << %(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 #{width.ceil} #{height.ceil + 20}" ) \
                 %(font-family="monospace" width="100%">\n)
          svg << %(<style>
            .blk { fill: #0f172a; stroke: #94a3b8; stroke-width: 1.6; }
            .wire { stroke: #94a3b8; stroke-width: 1.5; fill: none; }
            .wire.fb { stroke: #e0a458; }
            .arrow { fill: #94a3b8; } .arrow.fb { fill: #e0a458; }
            .lbl { fill: #64748b; font-size: 11px; }
            .glyph { fill: #f8fafc; font-size: 12px; }
            .sig { fill: #38bdf8; font-size: 11px; font-weight: bold; }
            .sig-input { fill: #fbbf24; font-size: 11px; font-weight: bold; }
            .sig-output { fill: #38bdf8; font-size: 11px; font-weight: bold; }
            .sig-monitor { fill: #c084fc; font-size: 11px; font-weight: bold; }
            .probe-glyph { stroke: #38bdf8; fill: none; stroke-width: 1.6; }
            .halo { fill: #0f172a; opacity: 0.82; }
            .blk-error { stroke: #e06553; stroke-width: 2.8; }
            .lbl-error { fill: #e06553; font-weight: bold; }
          </style>\n)

          lane_y_bottom = base_h
          top_lane_idx = 0
          @model.wires.each do |w|
            if @model.feedback_wires.includes?(w)
              lane_y_bottom += LANE_GAP
              draw_wire(svg, w, kind: :feedback, lane_y: lane_y_bottom)
            elsif top_wires_set.includes?(w)
              lane_y = MARGIN / 2 + top_lane_idx * LANE_GAP + LANE_GAP / 2
              top_lane_idx += 1
              draw_wire(svg, w, kind: :top, lane_y: lane_y)
            else
              draw_wire(svg, w, kind: :normal, lane_y: 0.0)
            end
          end

          blocks.each_with_index { |b, i| draw_block(svg, b, @boxes[i]) }
          svg << "</svg>\n"
        end
      end

      # Longest path from source blocks over the DAG (feedback edges removed).
      private def assign_layers : Array(Array(Int32))
        n = @model.blocks.size
        fwd = @model.wires.reject { |w| @model.feedback_wires.includes?(w) }
        adj = Array.new(n) { [] of Int32 }
        in_deg = Array(Int32).new(n, 0)
        fwd.each do |w|
          u = @model.block_index[w.src]
          v = @model.block_index[w.dst]
          adj[u] << v
          in_deg[v] += 1
        end

        layer = Array(Int32).new(n, 0)
        queue = Deque(Int32).new
        remaining = in_deg.dup
        n.times { |i| queue << i if remaining[i] == 0 }
        while node = queue.shift?
          adj[node].each do |v|
            layer[v] = {layer[v], layer[node] + 1}.max
            remaining[v] -= 1
            queue << v if remaining[v] == 0
          end
        end

        n_layers = n == 0 ? 0 : layer.max + 1
        cols = Array.new(n_layers) { [] of Int32 }
        n.times { |i| cols[layer[i]] << i }

        # one barycenter pass to reduce crossings
        preds = Array.new(n) { [] of Int32 }
        fwd.each { |w| preds[@model.block_index[w.dst]] << @model.block_index[w.src] }
        pos = Array(Float64).new(n, 0.0)
        cols.each_with_index do |col, li|
          col.each_with_index { |bi, r| pos[bi] = r.to_f } if li == 0
          next if li == 0
          col.sort_by! do |bi|
            ps = preds[bi]
            ps.empty? ? 0.0 : ps.sum { |p| pos[p] } / ps.size
          end
          col.each_with_index { |bi, r| pos[bi] = r.to_f }
        end
        cols
      end

      # Base size per category, grown vertically when a block has enough
      # ports that the default height would cram them closer than
      # MIN_PORT_SPACING apart (which would crowd their wire labels).
      MIN_PORT_SPACING = 22.0

      private def block_size(b : Block) : Tuple(Float64, Float64)
        w, h = case b.category
               when :source     then {92.0, 50.0}
               when :sum        then {44.0, 44.0}
               when :gain       then {64.0, 50.0}
               when :continuous then {140.0, 60.0}
               when :probe      then {48.0, 30.0}
               when :sink       then {110.0, 76.0}
               else                  {104.0, 52.0}
               end
        min_h = ({b.n_inputs, b.n_outputs}.max + 1) * MIN_PORT_SPACING
        {w, {h, min_h}.max}
      end

      # Extra room between stacked blocks when a SimResult is attached: a
      # sparkline is drawn below each normal wire's label (see draw_wire),
      # so the gap needs to fit label + sparkline instead of just the label.
      private def gap_y : Float64
        @result ? GAP_Y + 24.0 : GAP_Y
      end

      private def compute_boxes(cols : Array(Array(Int32)), top_offset : Float64, top_wires_set : Set(Wire))
        col_heights = cols.map do |col|
          col.sum { |bi| block_size(@model.blocks[bi])[1] } + gap_y * (col.size - 1)
        end
        max_h = col_heights.max? || 0.0
        top = MARGIN + top_offset

        x = MARGIN
        cols.each_with_index do |col, li|
          col_w = col.max_of { |bi| block_size(@model.blocks[bi])[0] }
          y = top + (max_h - col_heights[li]) / 2
          col.each do |bi|
            w, h = block_size(@model.blocks[bi])
            @boxes[bi] = Box.new(x + (col_w - w) / 2, y, w, h)
            y += h + gap_y
          end
          @col_x << {x, x + col_w}
          # The gap to the next column must fit the longest signal-label
          # caption of any direct (adjacent-column) wire crossing it —
          # otherwise a long display: caption, centered on the wire, would
          # overhang backward into the block it just left.
          x += col_w + required_gap(li, top_wires_set)
        end
      end

      private def required_gap(li : Int32, top_wires_set : Set(Wire)) : Float64
        widest_label = 0.0
        @model.wires.each do |w|
          next if @model.feedback_wires.includes?(w) || top_wires_set.includes?(w)
          si = @model.block_index[w.src]
          di = @model.block_index[w.dst]
          next unless @layer_of[si] == li && @layer_of[di] == li + 1
          next unless text = wire_label_text(w)
          widest_label = {widest_label, text.size * 6.5 + 16.0}.max
        end
        {GAP_X, widest_label}.max
      end

      private def wire_label_text(w : Wire) : String?
        return nil unless label = @model.wire_signal_label(w)
        "#{@model.wire_display(w) || label.to_s} (#{@model.wire_role(w)})"
      end

      # Column-wide clearance points for lane routing (see @col_x): always
      # outside every block in the column, regardless of how narrow the
      # specific source/destination block is compared to its siblings.
      private def exit_x(bi : Int32) : Float64
        @col_x[@layer_of[bi]][1] + 10.0
      end

      private def entry_x(bi : Int32) : Float64
        @col_x[@layer_of[bi]][0] - 10.0
      end

      private def draw_wire(svg : String::Builder, w : Wire, kind : Symbol, lane_y : Float64)
        si = @model.block_index[w.src]
        di = @model.block_index[w.dst]
        src_b = @model.blocks[si]
        dst_b = @model.blocks[di]
        sx, sy = @boxes[si].out_port(w.src_port, src_b.n_outputs)
        dx, dy = @boxes[di].in_port(w.dst_port, dst_b.n_inputs)
        cls = kind == :feedback ? "wire fb" : "wire"
        acls = kind == :feedback ? "arrow fb" : "arrow"
        lx = (sx + dx) / 2
        ly = {sy, dy}.min - 6

        case kind
        when :feedback, :top
          # :feedback loops backward (destination column is to the left of
          # the source's); :top skips forward over one or more intermediate
          # columns. Both route the same way: leave the source clear of
          # every block in ITS column (not just the source block itself,
          # which may be narrower than a sibling stacked in the same
          # column), travel through a dedicated lane above/below the whole
          # diagram, then enter clear of every block in the destination's
          # column. This never passes through a block, unlike the
          # one-bend router below, which only ever connects adjacent
          # columns (safe, since nothing else shares that gap).
          ex = exit_x(si)
          en = entry_x(di)
          svg << %(<path class="#{cls}" d="M#{r sx},#{r sy} H#{r ex} V#{r lane_y} H#{r en} V#{r dy} H#{r(dx - 8)}"/>\n)
          lx = (ex + en) / 2
          ly = lane_y - 5
        else
          if sy == dy
            svg << %(<path class="#{cls}" d="M#{r sx},#{r sy} H#{r(dx - 8)}"/>\n)
          else
            mid = (sx + dx) / 2
            svg << %(<path class="#{cls}" d="M#{r sx},#{r sy} H#{r mid} V#{r dy} H#{r(dx - 8)}"/>\n)
          end
        end
        svg << %(<polygon class="#{acls}" points="#{r dx},#{r dy} #{r(dx - 8)},#{r(dy - 4)} #{r(dx - 8)},#{r(dy + 4)}"/>\n)

        if text = wire_label_text(w)
          text_with_halo(svg, role_class(@model.wire_role(w)), lx, ly, esc(text))
          draw_sparkline(svg, w, kind, lx, ly) if kind == :normal
        end
      end

      # A compact inline trend line of the wire's own logged signal,
      # placed just below its label — only for normal (adjacent-column)
      # wires, whose extra vertical room (see #gap_y) is reserved
      # specifically for this. Lane wires (feedback/top) share tight,
      # stacked space that isn't set up to fit one, so they keep just the
      # label.
      SPARKLINE_POINTS = 48

      private def draw_sparkline(svg : String::Builder, w : Wire, kind : Symbol, lx : Float64, ly : Float64)
        return unless result = @result
        return unless label = @model.wire_signal_label(w)
        values = result.signals[label]?
        return unless values && values.size > 1

        # Downsample to a fixed point budget: a run can log thousands of
        # steps, but this trend line only ever renders at ~56x16px —
        # plotting every raw point would bloat the SVG for no visible gain.
        samples = if values.size <= SPARKLINE_POINTS
                    values
                  else
                    step = (values.size - 1) / (SPARKLINE_POINTS - 1).to_f
                    Array.new(SPARKLINE_POINTS) { |i| values[(i * step).round.to_i] }
                  end

        sw = 56.0
        sh = 16.0
        vmin = samples.min
        vmax = samples.max
        span = (vmax - vmin).abs < 1e-12 ? 1.0 : (vmax - vmin)
        n = samples.size
        pts = samples.each_with_index.map do |v, i|
          px = lx - sw / 2 + (i / (n - 1).to_f) * sw
          py = (ly + 14.0) - ((v - vmin) / span) * sh
          "#{r px},#{r py}"
        end.join(" ")
        color = role_color(@model.wire_role(w))
        svg << %(<polyline points="#{pts}" fill="none" stroke="#{color}" stroke-width="1.1" opacity="0.9"/>\n)
      end

      private def role_color(role : Symbol) : String
        case role
        when :input   then "#fbbf24"
        when :output  then "#38bdf8"
        when :monitor then "#c084fc"
        else               "#94a3b8"
        end
      end

      private def role_class(role : Symbol) : String
        {:input, :output, :monitor}.includes?(role) ? "sig-#{role}" : "sig"
      end

      private def draw_block(svg : String::Builder, b : Block, box : Box)
        tooltip = %(<title>#{b.name}: #{b.params_description}</title>)
        cx = box.x + box.w / 2
        blk_class = @highlight == b.name ? "blk blk-error" : "blk"

        case b.category
        when :sum
          rr = box.w / 2
          svg << %(<g>#{tooltip}<circle class="#{blk_class}" cx="#{r cx}" cy="#{r(box.y + rr)}" r="#{r rr}"/>)
          if b.is_a?(Blocks::Sum)
            b.signs.each_char_with_index do |c, i|
              _, py = box.in_port(i, b.n_inputs)
              sign = c == '+' ? "+" : "&#8722;"
              svg << %(<text class="glyph" x="#{r(box.x + 12)}" y="#{r(py + 4)}" text-anchor="middle">#{sign}</text>)
            end
          end
          svg << %(</g>\n)
        when :gain
          svg << %(<g>#{tooltip}<polygon class="#{blk_class}" points="#{r box.x},#{r box.y} #{r box.x},#{r(box.y + box.h)} #{r(box.x + box.w)},#{r(box.y + box.h / 2)}"/>) \
                 %(<text class="glyph" x="#{r(box.x + box.w * 0.34)}" y="#{r(box.y + box.h / 2 + 4)}" text-anchor="middle">#{esc(b.glyph_label)}</text></g>\n)
        when :probe
          svg << %(<g>#{tooltip}<rect class="#{blk_class}" x="#{r box.x}" y="#{r box.y}" width="#{r box.w}" height="#{r box.h}" rx="#{r(box.h / 2)}"/>) \
                 %(<path class="probe-glyph" d="M#{r(box.x + 10)},#{r(box.y + box.h / 2 + 4)} q6,-14 12,0 q6,14 12,0"/></g>\n)
        else
          svg << %(<g>#{tooltip}<rect class="#{blk_class}" x="#{r box.x}" y="#{r box.y}" width="#{r box.w}" height="#{r box.h}" rx="6"/>) \
                 %(<text class="glyph" x="#{r cx}" y="#{r(box.y + box.h / 2 + 4)}" text-anchor="middle">#{esc(b.glyph_label)}</text></g>\n)
        end

        text_with_halo(svg, @highlight == b.name ? "lbl-error" : "lbl", cx, box.y + box.h + 15,
          @highlight == b.name ? ":#{b.name} ⚠" : ":#{b.name}")
      end

      # Draws a translucent background rect sized to the (monospace) text
      # behind it, so a label stays readable even where it lands close to
      # a wire, another block, or another label — defense in depth on top
      # of the layout choices that avoid most overlaps outright.
      private def text_with_halo(svg : String::Builder, cls : String, x : Float64, y : Float64, text : String)
        halo_w = text.size * 6.5 + 6.0
        svg << %(<rect class="halo" x="#{r(x - halo_w / 2)}" y="#{r(y - 11.0)}" width="#{r halo_w}" height="14" rx="3"/>)
        svg << %(<text class="#{cls}" x="#{r x}" y="#{r y}" text-anchor="middle">#{text}</text>\n)
      end

      private def esc(s : String) : String
        s.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;")
      end

      private def r(v : Float64) : String
        v.round(1).to_s
      end
    end
  end
end
