module CrySim
  # Port reference in connect: :block (port 0) or {:block, port}.
  alias PortRef = Symbol | Tuple(Symbol, Int32)

  # Collects blocks, wires and solver settings inside a `CrySim.model`
  # block, then builds a validated Model. Block-declaration methods are
  # generated by the register_block macro; keyword arguments are forwarded
  # verbatim to the block constructor.
  class ModelBuilder
    def initialize(@name : String)
      @blocks = [] of Block
      @by_name = {} of String => Block
      @wires = [] of Wire
      @config = SolverConfig.new

      # ---- subsystem instantiation state (see "subsystems" section below) ----
      # Alias values are (final block name, port) — the same identity type
      # Wire uses — since a subsystem's inport/outport always resolve to a
      # real, prefixed block inside the template.
      @prefix = nil.as(String?)
      @inport_alias = {} of Symbol => Tuple(String, Int32)
      @outport_alias = {} of Symbol => Tuple(String, Int32)
      @pending_inport = nil.as(Tuple(String, Int32)?)
      @pending_outport = nil.as(Tuple(String, Int32)?)
    end

    # ---- solver configuration ----

    def duration(v : Number)
      @config.duration = v.to_f64
    end

    def dt(v : Number)
      @config.dt = v.to_f64
    end

    def method(m : Symbol)
      unless {:euler, :midpoint, :rk4}.includes?(m)
        raise ModelError.new("unknown solver method :#{m} (use :euler, :midpoint, or :rk4)")
      end
      @config.method = m
    end

    # ---- block registration ----

    def add_block(block : Block) : Block
      raise ModelError.new("duplicate block name :#{block.name}") if @by_name.has_key?(block.name)
      block.builder = self
      @blocks << block
      @by_name[block.name] = block
      block
    end

    # Prefixes an id with the current subsystem instance name (nil outside
    # a subsystem body), producing the block's final String identity. All
    # block-declaration methods and `connect` apply this transparently, so
    # DSL code written inside a subsystem template reads exactly like
    # top-level model code. A String, not a Symbol: Crystal symbols can't
    # be constructed dynamically (no `String#to_sym`), only literal ones
    # the user actually typed exist — see Wire's doc comment.
    private def prefixed(id : Symbol) : String
      pfx = @prefix
      pfx ? "#{pfx}.#{id}" : id.to_s
    end

    macro register_block(dsl_name, klass)
      def {{dsl_name.id}}(id : Symbol, **params)
        add_block({{klass}}.new(prefixed(id), **params))
      end
    end

    # sources
    register_block constant, Blocks::Constant
    register_block step, Blocks::Step
    register_block ramp, Blocks::Ramp
    register_block sine, Blocks::Sine
    register_block cosine, Blocks::Cosine
    register_block impulse, Blocks::Impulse
    register_block pulse, Blocks::Pulse
    register_block sawtooth, Blocks::Sawtooth
    register_block triangle, Blocks::Triangle
    register_block chirp, Blocks::Chirp
    register_block noise, Blocks::Noise

    # math
    register_block gain, Blocks::Gain
    register_block sum, Blocks::Sum
    register_block product, Blocks::Product
    register_block saturation, Blocks::Saturation
    register_block deadzone, Blocks::DeadZone
    register_block switch, Blocks::Switch
    register_block lookup_table, Blocks::LookupTable1D

    # continuous dynamics
    register_block integrator, Blocks::Integrator
    register_block unit_delay, Blocks::UnitDelay
    register_block rate_limiter, Blocks::RateLimiter
    register_block tf, Blocks::TransferFcn
    register_block pid, Blocks::PID

    # instrumentation & sinks
    register_block probe, Blocks::Probe
    register_block scope, Blocks::Scope

    # custom source: Proc form or eeeval expression form
    def signal(id : Symbol, fn : Proc(Float64, Float64))
      add_block(Blocks::SignalSource.new(prefixed(id), fn))
    end

    def signal(id : Symbol, *, expr : String)
      add_block(Blocks::ExprSource.new(prefixed(id), expr))
    end

    # custom transformation: Proc form or eeeval expression form
    def fn(id : Symbol, fn : Proc(Float64, Float64, Float64))
      add_block(Blocks::Fn.new(prefixed(id), fn))
    end

    def fn(id : Symbol, *, expr : String)
      add_block(Blocks::ExprFn.new(prefixed(id), expr))
    end

    # state-space block straight from matrices (row-major nested arrays).
    # `state_names:`/`output_names:` are optional readable labels: state
    # names are also auto-logged as extra signals (role :state) and shown
    # in the SVG tooltip in place of the raw state/output count.
    def ss(id : Symbol, *, a : Array(Array(Float64)), b : Array(Array(Float64)),
           c : Array(Array(Float64)), d : Array(Array(Float64)), x0 : Array(Float64)? = nil,
           state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      sys = CrySpace::StateSpace.new(a.to_tensor, b.to_tensor, c.to_tensor, d.to_tensor)
      add_block(Blocks::StateSpaceBlock.new(prefixed(id), sys, x0: x0, state_names: state_names, output_names: output_names))
    end

    # state-space block from an already-built CrySpace::StateSpace (e.g. the
    # result of balred, to_observability_form, augment_integrator, or a
    # discretization via sample(dt)). Dispatches automatically: a system
    # with dt == nil becomes a continuous StateSpaceBlock, a system with
    # dt set becomes a sampled DiscreteStateSpaceBlock — the same method
    # covers both without a separate keyword to remember.
    def ss(id : Symbol, *, sys : CrySpace::StateSpace, x0 : Array(Float64)? = nil,
           state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      if sys.dt
        add_block(Blocks::DiscreteStateSpaceBlock.new(prefixed(id), sys, x0: x0, state_names: state_names, output_names: output_names))
      else
        add_block(Blocks::StateSpaceBlock.new(prefixed(id), sys, x0: x0, state_names: state_names, output_names: output_names))
      end
    end

    # Parametric state-space block (PIANO_STATESPACE.md, Fase 5): matrix
    # entries as eeeval expressions of named parameters instead of literal
    # numbers, each compiled and evaluated once at build time against
    # `params` — the very same Hash(Symbol, Float64) that `use` binds for
    # parametric subsystems (see #use above), so a subsystem template can
    # forward its own `params` straight through:
    #
    #   spring_mass = CrySim.subsystem("spring_mass") do |sub, params|
    #     sub.ss :dynamics, a: [["0", "1"], ["-k/m", "-c/m"]], b: [["0"], ["1/m"]],
    #            c: [["1", "0"]], d: [["0"]], params: params
    #     sub.inport  :force,    to: :dynamics
    #     sub.outport :position, from: :dynamics
    #   end
    #   use spring_mass, as: :m1, k: 40.0, m: 2.0, c: 0.5
    #
    # or standalone, with a literal params hash and no subsystem at all:
    #
    #   ss :spring_mass, a: [["0", "1"], ["-k/m", "-c/m"]], b: [["0"], ["1/m"]],
    #      c: [["1", "0"]], d: [["0"]], params: {k: 40.0, m: 2.0, c: 0.5}
    #
    # x0/state_names/output_names stay literal — only the matrices are
    # parametric, since those are what differ between instances of the same
    # physical template.
    def ss(id : Symbol, *, a : Array(Array(String)), b : Array(Array(String)),
           c : Array(Array(String)), d : Array(Array(String)), params : Hash(Symbol, Float64),
           x0 : Array(Float64)? = nil, state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      env = param_env(params)
      sys = CrySpace::StateSpace.new(
        eval_matrix(id, a, env).to_tensor, eval_matrix(id, b, env).to_tensor,
        eval_matrix(id, c, env).to_tensor, eval_matrix(id, d, env).to_tensor)
      add_block(Blocks::StateSpaceBlock.new(prefixed(id), sys, x0: x0, state_names: state_names, output_names: output_names))
    end

    # Convenience overload for standalone use (outside any subsystem body):
    # `params:` as a NamedTuple literal — `params: {k: 40.0, m: 2.0, c: 0.5}`,
    # exactly as written in PIANO_STATESPACE.md's Fase 5 — instead of the
    # Hash(Symbol, Float64) a subsystem template already has on hand and
    # forwards directly to the overload above. Kept separate from a plain
    # `**params` double-splat on purpose: a physical parameter is very
    # plausibly named `a`, `b`, `c`, `d` or `x0` (the spring-mass-damper
    # example literally has a `c` for damping), which would collide with
    # this method's own matrix keywords.
    def ss(id : Symbol, *, a : Array(Array(String)), b : Array(Array(String)),
           c : Array(Array(String)), d : Array(Array(String)), params : NamedTuple,
           x0 : Array(Float64)? = nil, state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      hash = {} of Symbol => Float64
      params.each { |k, v| hash[k] = v.to_f64 }
      ss(id, a: a, b: b, c: c, d: d, params: hash, x0: x0, state_names: state_names, output_names: output_names)
    end

    # Shared by the parametric `ss` overload above: params, plus the same
    # named constants (pi, e, ...) every other eeeval expression in CrySim
    # (signal/fn `expr:`) already gets via EEEval::Constants::DEFAULT_ENV.
    private def param_env(params : Hash(Symbol, Float64)) : Hash(String, Float64)
      env = EEEval::Constants::DEFAULT_ENV.dup
      params.each { |k, v| env[k.to_s] = v }
      env
    end

    # Compiles and evaluates every cell of a matrix of eeeval expressions
    # once (matrices are static for an LTI system — no per-step
    # re-evaluation like signal/fn's `expr:` needs). Wraps eeeval's raw
    # "Undefined variable" exception in a ModelError naming the offending
    # block and expression, so a typo'd or missing param reads like the
    # rest of CrySim's builder errors instead of a bare eeeval message.
    private def eval_matrix(id : Symbol, matrix : Array(Array(String)), env : Hash(String, Float64)) : Array(Array(Float64))
      matrix.map do |row|
        row.map do |expr|
          begin
            EEEval::CalcFuncParser.compile(expr).evaluate(env)
          rescue ex
            raise ModelError.new("ss :#{id}: invalid matrix expression '#{expr}': #{ex.message}")
          end
        end
      end
    end

    # explicit discrete state-space block from matrices, sampled at dt:
    # x[k+1] = Ax[k] + Bu[k], y[k] = Cx[k] + Du[k].
    def dss(id : Symbol, *, a : Array(Array(Float64)), b : Array(Array(Float64)),
           c : Array(Array(Float64)), d : Array(Array(Float64)), dt : Number, x0 : Array(Float64)? = nil,
           state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      sys = CrySpace::StateSpace.new(a.to_tensor, b.to_tensor, c.to_tensor, d.to_tensor, dt.to_f64)
      add_block(Blocks::DiscreteStateSpaceBlock.new(prefixed(id), sys, x0: x0, state_names: state_names, output_names: output_names))
    end

    # Discretizes an already-declared continuous block (ss/tf) into a new,
    # separate dss block — sugar over pulling its `.state_space`, calling
    # CrySpace's `sample(dt, method:)`, and wrapping the result, all
    # without the round-trip through a built Model that
    # `state_space_of` needs (this runs during construction, straight off
    # the block registered so far). `from:` still needs its own inputs
    # connected like any other block (e.g. wired into the same source, to
    # compare continuous vs. discretized side by side) — this only reuses
    # its matrices, not its place in the wire graph.
    def discretize(id : Symbol, *, from src : Symbol, dt : Number, method : Symbol = :zoh,
                   x0 : Array(Float64)? = nil, state_names : Array(Symbol)? = nil, output_names : Array(Symbol)? = nil)
      src_name = prefixed(src)
      src_block = @by_name[src_name]? || raise ModelError.new("discretize: unknown source block :#{src}")
      sys = src_block.state_space || raise ModelError.new("discretize: block :#{src} has no state-space representation")
      raise ModelError.new("discretize: block :#{src} is already discrete (dt=#{sys.dt})") if sys.dt
      discretized = sys.sample(dt.to_f64, method: method)
      add_block(Blocks::DiscreteStateSpaceBlock.new(prefixed(id), discretized, x0: x0, state_names: state_names, output_names: output_names))
    end

    # generic escape hatch for user-defined Block subclasses. Not
    # auto-prefixed inside a subsystem body (the instance already carries
    # its final name) — prefix manually if it's used inside a `use`d
    # template.
    def block(b : Block) : Block
      add_block(b)
    end

    # ---- connections ----

    # `role` overrides the automatic input/output/monitor classification
    # (see Model#wire_role); `display` sets a human-readable caption shown
    # in the SVG diagram and in plots in place of the signal name. Bare
    # symbols are resolved against subsystem instance aliases first (see
    # "subsystems" below), then prefixed for the current subsystem body —
    # so both a top-level `connect :sensor, to: :err` and a `connect
    # :something, to: :m1` targeting a `use`d instance work the same way.
    def connect(src : PortRef, *, to dst : PortRef, as label : Symbol? = nil,
               role : Symbol? = nil, display : String? = nil)
      src_name, src_port = resolve_source(src)
      dst_name, dst_port = resolve_dest(dst)
      wire_connect(src_name, src_port, dst_name, dst_port, label.try(&.to_s), role, display)
    end

    # `feedback` is `connect` under a name that signals intent: this wire
    # closes a loop. Purely for readability — CrySim detects feedback
    # edges structurally (a DFS back-edge, see Model#find_feedback_wires)
    # regardless of which method created the wire, so this changes nothing
    # about how the model behaves or renders.
    def feedback(*, from src : PortRef, to dst : PortRef, as label : Symbol? = nil,
                role : Symbol? = nil, display : String? = nil)
      connect(src, to: dst, as: label, role: role, display: display)
    end

    # Low-level wire creation from already-resolved, final block names —
    # no prefixing, no alias lookup. This is what `connect` calls after
    # resolving user-facing symbols, and what `Block#>>` calls directly
    # with a block's own (already-final) `.name`, so chaining inside a
    # subsystem body never gets double-prefixed.
    def wire_connect(src_name : String, src_port : Int32, dst_name : String, dst_port : Int32,
                     label : String? = nil, role : Symbol? = nil, display : String? = nil)
      unless @by_name.has_key?(src_name)
        raise ModelError.new("connect: unknown source block :#{src_name}")
      end
      dst_block = @by_name[dst_name]?
      raise ModelError.new("connect: unknown destination block :#{dst_name}") unless dst_block

      # sinks grow one input port per incoming wire
      if dst_block.elastic_inputs?
        dst_port = dst_block.n_inputs
        dst_block.n_inputs += 1
      end

      @wires << Wire.new(src_name, src_port, dst_name, dst_port, label, role, display)
    end

    # Bare (id, port) exactly as the user typed it — no prefixing, no
    # alias lookup yet.
    private def resolve(ref : PortRef) : Tuple(Symbol, Int32)
      case ref
      in Symbol                then {ref, 0}
      in Tuple(Symbol, Int32) then ref
      end
    end

    private def resolve_source(ref : PortRef) : Tuple(String, Int32)
      name, port = resolve(ref)
      @outport_alias[name]? || {prefixed(name), port}
    end

    private def resolve_dest(ref : PortRef) : Tuple(String, Int32)
      name, port = resolve(ref)
      @inport_alias[name]? || {prefixed(name), port}
    end

    # ---- subsystems ----
    #
    # A Subsystem (see subsystem.cr) is a reusable, parametric block
    # template. `use` instantiates it: every block declared inside the
    # template body is inlined into THIS model with its name prefixed by
    # the instance name (`"m1.dynamics"`), and the template's single
    # inport/outport become usable from the outside as the instance name
    # itself — `connect :something, to: :m1` / `connect :m1, to: :else`.
    # Resolved entirely here, at build time: by the time Model.new runs,
    # every wire already references real, prefixed block names — Model
    # itself never needs to know subsystems exist.
    #
    # v0.2 scope: exactly one inport and one outport per subsystem
    # (SISO). Multi-port subsystems are deferred until vector/bus signals
    # (Mux/Demux) land, since richer port aliasing wants the same
    # groundwork.
    def use(sub : Subsystem, as prefix : Symbol, **params)
      hash = {} of Symbol => Float64
      params.each { |k, v| hash[k] = v.to_f64 }
      sub.instantiate(self, prefix, hash)
    end

    # Declares the template's single external input: `to:` names a block
    # (inside this same template) that receives the instance's incoming
    # wire. Only valid inside a subsystem body.
    def inport(id : Symbol, *, to dst : PortRef)
      raise ModelError.new("inport can only be declared inside a subsystem body") unless @prefix
      raise ModelError.new("subsystem :#{@prefix} declares more than one inport (v0.2 supports exactly one)") if @pending_inport
      name, port = resolve(dst)
      @pending_inport = {prefixed(name), port}
    end

    # Declares the template's single external output: `from:` names a
    # block (inside this same template) whose output feeds the instance's
    # outgoing wires. Only valid inside a subsystem body.
    def outport(id : Symbol, *, from src : PortRef)
      raise ModelError.new("outport can only be declared inside a subsystem body") unless @prefix
      raise ModelError.new("subsystem :#{@prefix} declares more than one outport (v0.2 supports exactly one)") if @pending_outport
      name, port = resolve(src)
      @pending_outport = {prefixed(name), port}
    end

    # Called by Subsystem#instantiate around the template body.
    def begin_subsystem(prefix : Symbol)
      raise ModelError.new("nested subsystems are not supported (already inside :#{@prefix})") if @prefix
      raise ModelError.new("subsystem instance name :#{prefix} is already used") if @by_name.has_key?(prefix.to_s) || @inport_alias.has_key?(prefix)
      @prefix = prefix.to_s
      @pending_inport = nil
      @pending_outport = nil
    end

    def end_subsystem(prefix : Symbol)
      pi = @pending_inport || raise ModelError.new("subsystem :#{prefix} must declare exactly one inport")
      po = @pending_outport || raise ModelError.new("subsystem :#{prefix} must declare exactly one outport")
      @inport_alias[prefix] = pi
      @outport_alias[prefix] = po
      @prefix = nil
    end

    def build : Model
      Model.new(@name, @blocks, @wires, @config)
    end
  end
end
